version: '2'
services:
  cas:
    build:
      context: .
      args:
        LDAP_PORT: ${LDAP_PORT:-389}
        LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
    container_name: cas
    ports:
      - "${CAS_PORT:-8443}:8443"
    restart: unless-stopped
    networks:
      - openldap

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    volumes:
      - ./ldap-storage/ldap_db:/var/lib/ldap
      - ./ldap-storage/ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=example-org
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD:-config}
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    networks:
      - openldap
    ports:
      - '${LDAP_PORT:-389}:389'

  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.9
    container_name: openldap-ui
    environment:
      - LDAP_URI=ldap://openldap
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_BIND_PWD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - ACCEPT_WEAK_PASSWORDS=TRUE
      - USERNAME_REGEX=^[a-zA-Z0-9._-]{3,32}$
      - SERVER_HOSTNAME=localhost:${LDAP_UI_PORT:-18080}
    depends_on:
      - openldap
    ports:
      - ${LDAP_UI_PORT:-18080}:80
    networks:
      - openldap

networks:
  openldap:
    name: openldap