info:
  description: CAS Configuration

cas:
  authn:
    accept:
      enabled: false
    ldap[0]:
      bind-dn: cn=admin,dc=example,dc=org
      bind-credential: admin
      base-dn: ou=people,dc=example,dc=org
      search-filter: uid={user}
      password-encoder:
        type: NONE
      ldap-url: ldap://host.docker.internal:389
      use-start-tls: false
      type: AUTHENTICATED