info:
  description: CAS Configuration

cas:
  service-registry:
    core:
      init-from-json: true
  authn:
    accept:
      enabled: false
    ldap[0]:
      bind-dn: cn=admin,dc=example,dc=org
      bind-credential: ldap_admin_password
      base-dn: ou=people,dc=example,dc=org
      search-filter: cn={user}
      password-encoder:
        type: NONE
      ldap-url: ldap://openldap:ldap_port
      use-start-tls: false
      type: AUTHENTICATED